### ISSUE TITLE
Unit testing for PyPDF2

### ISSUE THREAD

**Issue by snorfalorpagus** [mstamy2/PyPDF2#117]
PyPDF2 doesn't seem to have any automated testing in the build.

Adding some unit tests could help to prevent regressions [like this one](https://github.com/mstamy2/PyPDF2/pull/116).

I'd be happy to get started with this if there is agreement that 1) this would be useful, and 2) which testing library to use. We could make use of the PDFs in the PDF_Samples directory.

**Comment by MartinThoma** [comment]
I've just added a couple of unit tests + CI with github actions and pytest. More tests are welcome!
