### ISSUE TITLE
getNumPages() don't always return the good number of pages

### ISSUE THREAD

**Issue by Brunus-V** [mstamy2/PyPDF2#128]
Hi,
I'm prety new with Python but I'm using PyPDF2 to process PDF files.
I found something annoying with some PDFs I'm processing :  getNumPages() fails to return the good number of pages.
I have a PDF to provide if you want to test the code below against pdfinfos command or GIMP/Inskcape.
My test code as pdfprob.py : 

/***********************************************************/
/*       pdfprob.py     */
import sys, getopt, os
from pyPdf import PdfFileReader

bookFileName = sys.argv[1]
print bookFileName

if os.path.isfile(bookFileName) :
    bookPdf = PdfFileReader(file(bookFileName, "rb"))
    bookPagesNumber = bookPdf.getNumPages()
    print "Page number : " + str(bookPagesNumber)
/*     end of python script     */
/***************************************************************/

exemple of use : 
> pdfprobe.py book.pdf
book.pdf
Page number : 11

While : 
> pdfinfo book.pdf
Creator:        Adobe InDesign CC (Windows)
Producer:       Adobe PDF Library 11.0
CreationDate:   Thu Apr 17 15:13:09 2014
ModDate:        Thu Apr 17 15:34:33 2014
Tagged:         no
Form:           none
Pages:          12
Encrypted:      no
Page size:      595.2 x 841.92 pts (A4)
Page rot:       0
File size:      2799468 bytes
Optimized:      no
PDF version:    1.6

**Comment by chrisinmtown** [comment]
Maybe this issue could be closed?
