### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by akaiame** [mstamy2/PyPDF2#171]
Python 3.4.2 and PyPDF2 1.24 (also using reportlab 3.1.44 in case that helps)

I recently upgraded from Python 2.7 to 3.4, and am in the process of porting my code. This code is used to create a blank pdf page with links embedded in it (using reportlab) and merge it (using PyPDF2) with an existing pdf page. I had an issue with reportlab in that saving the canvas used StringIO which needed to be changed to BytesIO, but after doing that I ran into this error:

Traceback (most recent call last):
  File "C:\cms_software\pdf_replica\builder.py", line 401, in merge_pdf_files
    input_page.mergePage(link_page)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2013, in mergePage
    self._mergePage(page2)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2059, in _mergePage
    page2Content = PageObject._pushPopGS(page2Content, self.pdf)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1973, in _pushPopGS
    stream = ContentStream(contents, pdf)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2446, in __init__
    stream = BytesIO(b_(stream.getData()))
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 826, in getData
    decoded._data = filters.decodeStreamData(self)
  File "C:\Python34\lib\site-packages\PyPDF2\filters.py", line 326, in decodeStreamData
    data = ASCII85Decode.decode(data)
  File "C:\Python34\lib\site-packages\PyPDF2\filters.py", line 264, in decode
    data = [y for y in data if not (y in ' \n\r\t')]
  File "C:\Python34\lib\site-packages\PyPDF2\filters.py", line 264, in <listcomp>
    data = [y for y in data if not (y in ' \n\r\t')]
TypeError: 'in < string >' requires string as left operand, not int

Here is the line and the line above where the traceback mentions:

link_page = self.make_pdf_link_page(pdf, size, margin, scale_factor, debug_article_links)
if link_page != None:
       input_page.mergePage(link_page)

Here are the relevant parts of that make_pdf_link_page function:

packet = io.BytesIO()
can = canvas.Canvas(packet, pagesize=(size['width'], size['height']))
...(creates a new PDF with Reportlab that has the url link embedded)
can.linkURL(url, r1, thickness=1, color=colors.green)
can.rect(x1, y1, width, height, stroke=1, fill=0)
can.save()
packet.seek(0)
try:
     new_pdf = PdfFileReader(packet)
except Exception as e:
            logger.exception('e')
            return None
return new_pdf.getPage(0)

UPDATE:
I've located the problem! It is with the ASCII85Decode class. It's not returning bytes, but should be. I borrowed the code for this same type from pdfminer3k, and this works perfectly. Here is the code from pdfminer3k plugged into the PyPDF2 class:

class ASCII85Decode(object):
    def decode(data, decodeParms=None):
        if isinstance(data, str):
            data = data.encode('ascii')
        n = b = 0
        out = bytearray()
        for c in data:
            if ord('!') <= c and c <= ord('u'):
                n += 1
                b = b*85+(c-33)
                if n == 5:
                    out += struct.pack(b'>L',b)
                    n = b = 0
            elif c == ord('z'):
                assert n == 0
                out += b'\0\0\0\0'
            elif c == ord('~'):
                if n:
                    for _ in range(5-n):
                        b = b*85+84
                    out += struct.pack(b'>L',b)[:n-1]
                break
        return bytes(out)

This class needs to return bytes for Python 3 users. Please make this change. Thank you!
Related to #172

**Comment by msom** [comment]
+1

**Comment by keson** [comment]
i wanted to post original filters.ASCII85Decode.decode ported to 3.4, but pdfminer3k decode is so much simpler !
to make it work with both 3.4 and 2.7

if isinstance(data, str):
    data = data.encode('ascii')

should be changed to:
if isinstance(data, str):
    data = bytearray(data)


regards!

**Comment by elmcrest** [comment]
+1

**Comment by mstamy2** [comment]
Should be fixed with #172
