### ISSUE TITLE
Image resources getting lost after merge

### ISSUE THREAD

**Issue by pennersr** [mstamy2/PyPDF2#182]
When merging 2 PDFs with two unique barcode images, the merged result visually contains two images, but in fact they are both the same. One image is lost.

Example code and files that demonstrate the problem can be found here:

https://github.com/pennersr/PyPDF2/tree/label-merge-hotfix/Sample_Code/label-merge-hotfix

The merge.pdf is the result of a merger of 0.pdf and 1.pdf (via `merge.py`). Visually, it looks good, but if you would open up a barcode scanner (any mobile phone based scanner app will do) and actually scan the barcodes you'll find that the barcode image on the righ-hand label with code 323210745259903893864030 is actually identical to the one on the left.

A workaround for this issue that "works for us" is the following:

https://github.com/pennersr/PyPDF2/blob/label-merge-hotfix/PyPDF2/pdf.py#L1948

Though I must admit I am not sure if this is the way to go...

**Comment by mstamy2** [comment]
Thank you for the well-documented issue. Glad you found that renaming all resources worked as a hotfix. Commit 7456f0a should provide a more concrete solution.

`newRes[key] != page2Res[key]`
returns `False`, which results in overwriting rather than renaming.
`newRes.raw_get(key) != page2Res.raw_get(key)`
returns `True` to correctly rename the resources.

**Comment by pennersr** [comment]
Thanks for fixing!

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
