### ISSUE TITLE
Corrupt output after mergePage on some PDF's

### ISSUE THREAD

**Issue by dwsc** [mstamy2/PyPDF2#192]
I use mergePage to stamp some text on the top of a page.  Simplified, here is the code:
```
import StringIO
from PyPDF2 import PdfFileWriter, PdfFileReader

package = PdfFileReader('original.pdf')
stamp = PdfFileReader('stamp.pdf')
writer = PdfFileWriter()

output = open('output.pdf', 'wb')
for page in package.pages:
	page.mergePage(stamp.getPage(0))
	writer.addPage(page)

writer.write(output)
output.close()
```
Some original PDF's output is invalid (message when opening in some versions of Acrobat (not reader).  I cannot seem to find what differences in the original PDF are causing the problem.  

Files used in this example [can be found here](https://www.dropbox.com/sh/gi3wm7mmurfyeql/AAAy3tkOxuDHzdG0EqT9M6ANa?dl=0)

**Comment by christianfvn** [comment]
I'm experiencing the same problem. Both my package and stamp pdf files write fine to the PdfFileWriter class, but when merging the pages, the output is corrupted.

**Comment by mstamy2** [comment]
See if commit fc05b046c05d9cf5c9cbbe67b12ffef7501babc7 resolves the issue for you. I was able to correctly merge the files provided with this change.

However, the process still hangs in Python 3 (and eventually throws an error if you're patient).
I'll work on this issue along with bookmark transfer.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by Rob1080** [comment]
Still an issue in some pdfs when using mergePage.

**Comment by indra589** [comment]
Yes, I can see that this issue still persist. Not sure but I see that the trend is higher when PDFs are more than 1.5 MB size. Is there any solution to this or is there a different page to refer?

**Comment by indra589** [comment]
@claird and @mstamy2 , any idea if this can be addressed by a work around.

**Comment by AxSch** [comment]
This is still an issue - why has this been closed??

**Comment by sncalvo** [comment]
Any updates on this? I have experienced the same issue

**Comment by MartinThoma** [comment]
@sncalvo with which version? Which code? Which pdf?

**Comment by JulianDicken** [comment]
Also having this issue

**Comment by pubpub-zz** [comment]
@JulianDicken 
Which version ? which code? which pdf ?

**Comment by JulianDicken** [comment]
actually this was on me -- pdf files I tried to merge didnt exist, resulting in an empty pdf
Granted a warning for merging empty or nonexistent pdf files should be thrown IMO
