### ISSUE TITLE
mergeTranslatedPage hangs

### ISSUE THREAD

**Issue by jvalenzuela** [mstamy2/PyPDF2#199]
Having a problem with merging pages. Here's some quick code that reproduces the issue:

import PyPDF2

reader = PyPDF2.PdfFileReader('050.pdf')
orig = reader.getPage(0)
new = PyPDF2.pdf.PageObject.createBlankPage(width=orig.mediaBox[2],
                                            height=orig.mediaBox[3])
new.mergeTranslatedPage(orig, 0, 0)

I don't know how to attach the 050.pdf document which is causing the problem, but contact me via email and I'll send it. It's a single page, about 1.3MB. Running this test just eats up CPU and memory, never seeming to complete.

Thanks,
Jason Valenzuela

**Comment by mstamy2** [comment]
Resolved through email. Do send me the files if they cause further problems for you.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
