### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by chithrabunni** [mstamy2/PyPDF2#205]
ubuntu@ubuntu:~/androwarn$ sudo python androwarn.py -i 1m_cracked_2_air.air.Ending_quickdownload_309.apk -r html -v 3 -n
[sudo] password for ubuntu: 
Traceback (most recent call last):
  File "androwarn.py", line 116, in <module>
    main(options, arguments)
  File "androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/home/ubuntu/androwarn/androwarn/analysis/analysis.py", line 115, in perform_analysis
    ( 'device_settings_harvesting', 			 gather_device_settings_harvesting(x) ),
  File "/home/ubuntu/androwarn/androwarn/search/malicious_behaviours/device_settings.py", line 96, in gather_device_settings_harvesting
    result.extend( detect_get_package_info(x) )
  File "/home/ubuntu/androwarn/androwarn/search/malicious_behaviours/device_settings.py", line 79, in detect_get_package_info
    flags = recover_bitwise_flag_settings(flag, PackageManager_PackageInfo)
  File "/home/ubuntu/androwarn/androwarn/util/util.py", line 257, in recover_bitwise_flag_settings
    if (int(flag) & option_value) == option_value :
ValueError: invalid literal for int() with base 10:
![screenshot from 2015-06-09 16 18 10](https://cloud.githubusercontent.com/assets/12812255/8056166/28043f5e-0ec3-11e5-9818-3f7701f1886a.png)
 'Lcom/google/android/gms/internal/ry;->a(Landroid/content/Context;)Z'

I encountered this error when i triend to run Androwarn.

python androwarn.py -i 1m_cracked_2_air.air.Ending_quickdownload_309.apk -r html -v 3 -n

This is the command i used to run Androwarn
Kindly provide a solution.

**Comment by mstamy2** [comment]
Hello,

You might report this in the [androwarn](https://github.com/maaaaz/androwarn) repository.

I don't see any immediate PyPDF2 issues here - but please elaborate if there are.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
