### ISSUE TITLE
global name 'Str' is not defined

### ISSUE THREAD

**Issue by martinmaillard** [mstamy2/PyPDF2#213]
After upgrading to 1.25, I encountered the following error:

    Traceback (most recent call last):
      [...]
      File "./venv/lib/python2.7/site-packages/PyPDF2/merger.py", line 203, in append
        self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
      File "./venv/lib/python2.7/site-packages/PyPDF2/merger.py", line 151, in merge
        outline = pdfr.getOutlines()
      File "./venv/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1333, in getOutlines
        outline = self._buildOutline(node)
      File "./venv/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1416, in _buildOutline
        elif isinstance(dest, Str) and dest in self._namedDests:
    NameError: global name 'Str' is not defined

**Comment by mstamy2** [comment]
Does commit 736dc274537d3639b72a9deebabe9e0d1fa470d0 resolve this?

**Comment by martinmaillard** [comment]
Yes it does !

**Comment by mstamy2** [comment]
I'll update PyPI with this patch as well.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
