### ISSUE TITLE
How do I access information for inline images?

### ISSUE THREAD

**Issue by jbarlow83** [mstamy2/PyPDF2#214]
I'd like to parse PDF pages to obtain information about any inline images they contain.

I've gone this far:

``` python
import PyPDF2 as pypdf
pdf = pypdf.PdfFileReader('inline.pdf')
page = pdf.pages[0]
contents = page.getContents()
data = c.getData()
```

`data` now contains bytes representing an inline image. What I'd like to do is route this through something like _parseInlineImages – except that is a private function. Is there some other way to get at this information without needing to replicate the existing parser?

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
