### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by dipankar08** [mstamy2/PyPDF2#217]
I am getting the below error :

 File "/home/dipankar/craZyeXp/MiniProjects/genApps/CommonLib/pdfBookGenerator/genPdfBook.py", line 61, in buildRecursive
    cbm = output.addBookmark('Q #'+str(v1),HashQuestionStartLine[v1] , parent=bm)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 535, in addBookmark
    pageRef = self.getObject(self._pages)['/Kids'][pagenum]
IndexError: list index out of range

**Comment by mstamy2** [comment]
Hello,

Can you check that you're passing a valid page number number, and that you've added the necessary pages to the output?

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
