### ISSUE TITLE
Rotated Document 114x The Size Of Original Document

### ISSUE THREAD

**Issue by whitemice** [mstamy2/PyPDF2#218]
Rotating the pages of a document and writing out the document produces a document 114x the size of the original document.

    signal.signal(signal.SIGALRM, timeout_alarm_handler)
    signal.alarm(15)

    reader = PdfFileReader(self.rfile, strict=False, )
    writer = PdfFileWriter()

    for pagenum in range(reader.numPages):
        try:
            signal.alarm(15)
            page = reader.getPage(pagenum)
            if not self._counter_clockwise:
                page.rotateClockwise(self._rotate_degrees)
            else:
                page.rotateCounterClockwise(self._rotate_degrees)
            page.compressContentStreams()
            writer.addPage(page)
            signal.alarm(0)
            page = None
        except TimeOutAlarm:
            raise BurstingTimeOutException
        else:
            writer.write(self.wfile)
    writer = None

**Comment by whitemice** [comment]
is this issue potentially related to lack of compression support? #157

**Comment by whitemice** [comment]
Example document @ http://www.wmmi.net/documents/Bugs/PyPDF-114xSizeAfterRotation-Example.pdf  
Cannot upload a document of PDF to issue

**Comment by whitemice** [comment]
Issue is not related to rotation; even if the page is read and then insert into the writer with no modification the bloat occurs.

**Comment by dhudson1** [comment]
Because I test Python on a Windows machine, I had to come up with a screwy, roundabout way to get the same functionality that the signal module offers POSIX compliant OSes.

Anyway, when I ran the code below, I did not notice any change in size of the PDF. This could be for any number of reasons, but at least it worked for me.

Here it is:
```python
from PyPDF2 import PdfFileReader, PdfFileWriter
import multiprocessing
import os


# Exceptions used only when the time has been exceeded

class TimeOutAlarm(Exception):
    pass

class RotationTimeOutException(Exception):
    pass

# Used only for rotating and compressing the file in the process

def doEverything(filename,
                 pagenum,
                 outputfilename,
                 rotateClockwise = True,
                 degreesToRotate = 90):

    # Make the writer, temporary read file,
    # the reader, and get the requested page

    writer = PdfFileWriter()
    tmpInput = open(filename, "rb")
    reader = PdfFileReader(tmpInput)
    page = reader.getPage(pagenum)

    # Rotate the page however appropriate

    if rotateClockwise:
        page.rotateClockwise(degreesToRotate)
    else:
        page.rotateCounterClockwise(degreesToRotate)

    # Compress the page

    page.compressContentStreams()

    # Add the page to the writer

    writer.addPage(page)

    # Open up the writing file and write
    # to it

    tmpOutput = open(outputfilename, "wb")
    writer.write(tmpOutput)

    # Close the files

    tmpOutput.close()
    tmpInput.close()

if __name__ == "__main__":

    # Timeout for reading a PDF

    timeout = 15

    # filename for the file to be rotated and compressed

    fileInput = "PyPDF-114xSizeAfterRotation-Example.pdf"

    # Temporary output file for storing each page

    tmpFileOutput = "~tmpoutputfile%d.pdf"

    # Final output file for storing the rotatation

    fileOutput = "working_test_output.pdf"

    # Open the temporary input file

    tmpInput = open(fileInput, "rb")

    # Make the PDF Reader and Writer

    reader = PdfFileReader(tmpInput)
    writer = PdfFileWriter()

    # Find the range of pages

    rang = range(reader.numPages)

    # Close the temporary input file

    tmpInput.close()

    # Delete the PDF Reader object

    del reader

    # Iterate through the range of pages

    for pagenum in rang:
        try:
            process = multiprocessing.Process(
                name="do-everything", # The name of the process (Not needed)
                target=doEverything,  # The Target Function
                args=                 # The args to Pass
                (   fileInput,                # Input filename
                    pagenum,                  # Current Page Number
                    tmpFileOutput%pagenum,    # Temporary output filename
                    True,                     # Direction to Rotate
                    90))                      # Degrees To Rotate

            # Start the Process

            process.start()

            # End the Process after 15 Seconds and raise an alarm

            process.join(timeout)
            if process.is_alive():
                process.terminate()
                raise TimeOutAlarm("It took longer than %d seconds." % timeout)

        except TimeOutAlarm:

            # Since the alarm was raised, throw an appropriate
            # exception to exit the loop

            raise RotationTimeOutException

    # List of open file objects, used for appropriately
    # closing files and deleting them

    listOfFiles = []

    for pagenum in rang:

        # Open each file, put it in the list, read everything
        # from it, and put all the pages in the writer

        try:
            tmpInput = open(tmpFileOutput%pagenum, "rb")
            reader = PdfFileReader(tmpInput)
            for pn in range(reader.numPages):
                writer.addPage(reader.getPage(pn))
            listOfFiles.append(tmpInput)
            reader = None
        except:
            print("Could not find file", tmpFileOutput%pagenum)

    # Output open file object

    tmpOutput = open(fileOutput, "wb")

    # Write the file

    writer.write(tmpOutput)
    writer = None

    # Remove all of the excess bits of files by
    # iterating through the list of the range of
    # pages of the original document
    for filenum in rang:
        try:
            tmpInput = listOfFiles[filenum]
            tmpInput.close()
            os.remove(tmpFileOutput%filenum)
        except:
            print("Could not remove file", tmpFileOutput%filenum)

    # Cose the final remaining open file object

    tmpOutput.close()
```
Please comment if this does not work for you. I am rather new to PyPDF2, but I will do my best.

**Comment by whitemice** [comment]
This works well enough; the result of the document of the rotated pages is within a reasonable margin [less than 2x] the source document.  Used a slightly different approach: I kept the file handles in a list, but same concept.

    signal.signal(signal.SIGALRM, timeout_alarm_handler)
    signal.alarm(15)

    reader = PdfFileReader(self.rfile, strict=False, )

    page_files = list()

    """
    Each page is rotated to a unique document, keeping the reference to
    the file in page_files.  The reader is disposed after processing
    each page.  Subsequently each page is composed back into a single file.
    This enables PyPDF to do a much more efficient sweeping of document
    resources - if the rotated pages are composed directly to the target
    document a large amount of redundant information ends up in the target
    file which can be a file orders of magnitude larger than the source
    document.
    """

    for pagenum in range(reader.numPages):
        try:
            signal.alarm(15)
            page = reader.getPage(pagenum)
            if not self._counter_clockwise:
                page.rotateClockwise(self._rotate_degrees)
            else:
                page.rotateCounterClockwise(self._rotate_degrees)
            page.compressContentStreams()

            writer = PdfFileWriter()
            writer.addPage(page)
            page_file = BLOBManager.ScratchFile()
            writer.write(page_file)
            page_files.append(page_file)
            del writer
            page = None

            signal.alarm(0)

        except TimeOutAlarm:
            raise PageRotationTimeoutException

    del reader

    writer = PdfFileWriter()  # create writer for composite document
    for page_file in page_files:
        page_file.seek(0)
        reader = PdfFileReader(page_file, strict=False, )
        writer.addPage(reader.getPage(0))
        del reader

    writer.write(self.wfile)
    del writer

    """
    Page file MUST be closed AFTER the writer writes, otherwise you
    will fail with an "I/O operation on closed file" during the writer's
    call to self._sweepIndirectReferences(externalReferenceMap, self._root)
    """
    for page_file in page_files:
        BLOBManager.Close(page_file)

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
