### ISSUE TITLE
PyPDF hangs indefinitely when trying to open a malformatted file

### ISSUE THREAD

**Issue by bepetersn** [mstamy2/PyPDF2#224]
This file is clearly malformatted/corrupted, as my computer reports it at only 77 bytes. However, I still would prefer that the program exited than to go forever. Thanks for your help!

Here is the stacktrace produced when after a long time, I killed the process:

    ^CTraceback (most recent call last):
    File "<stdin>", line 1, in <module>    
    File "/home/brian/.virtualenvs/xxx/lib/python2.7/site-packages/PyPDF2/pdf.py", line 913, in __init__
      self.read(stream)
    File "/home/brian/.virtualenvs/xxx/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1464, in read
      line = self.readNextEndLine(stream)
    File "/home/brian/.virtualenvs/xxx/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1721, in readNextEndLine
      line = x + line
    KeyboardInterrupt

Link to the file:
https://www.dropbox.com/s/unb0yhii7cgv69c/WU%2C%20Hellweger.pdf?dl=0

**Comment by bepetersn** [comment]
Looks like an earlier issue / merge fixes this, sorry!

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaiksihwar@gmail.com
