### ISSUE TITLE
ValueError: invalid literal for int() with base 10: "5347+01'00')>>"

### ISSUE THREAD

**Issue by StErMi** [mstamy2/PyPDF2#262]
Hi

I've got a problem while reading (to merge with another) a PDF. This is the instruction that will generate the error:

``` python
pdf_merger.append(PdfFileReader(temp_file, strict=False), import_bookmarks=False)
```

This is the stacktrace:

```
pdf_merger.append(PdfFileReader(temp_file, strict=False), import_bookmarks=False)
  File "C:\Users\Emanuele\Envs\tr\lib\site-packages\PyPDF2\pdf.py", line 1065, in __init__
    self.read(stream)
  File "C:\Users\Emanuele\Envs\tr\lib\site-packages\PyPDF2\pdf.py", line 1774, in read
    idnum, generation = self.readObjectHeader(stream)
  File "C:\Users\Emanuele\Envs\tr\lib\site-packages\PyPDF2\pdf.py", line 1638, in readObjectHeader
    return int(idnum), int(generation)
ValueError: invalid literal for int() with base 10: "5347+01'00')>>"
```

Unfortunately I cannot share the test PDF becuase has some sensitive data. What I can tell it's that has a lot of whitespaces in the latest page.

I'm using the latest version of PyPDF2 installed via PIP: PyPDF2==1.25.1

**Comment by mstamy2** [comment]
See my comment from #183

You're welcome to send me the PDF privately, and I can work with it securely.

If that's not an option, then locating the line in the file that PyPDF2 crashes on and sending a snippet would be beneficial as well.

**Comment by MartinThoma** [comment]
Nothing was added and thus this is impossible for me to fix. I'll close it.
