### ISSUE TITLE
Corrupted PDF in 1.26 when older versions throw "ValueError: I/O operation on closed file"

### ISSUE THREAD

**Issue by TheFrostyboss** [mstamy2/PyPDF2#263]
So I was using v 1.26 to splice/merge different pages of different PDFs together, and invariably most of the pages would be corrupted when I output them (e.g. reader would display a blank page and say "There is an error displaying this page", or some pages might retain the same structure as the original PDF, but portions of the page would be populated with random text).

When I rolled back to 1.24-1.25, the same code produced a "ValueError: I/O operation on closed file", presumably for trying to write out pages from PDFs I had closed after reading them in.  

Basically, trying to debug this kind of error in the current version is extremely difficult, especially to someone not familiar with PyPDF2.  That is, I would always rather get some kind of error to point me in the right direction, rather than just a corrupted output.

The original code:

```
full_path = r"path_to_pdf.pdf"
full_path2 = full_path.replace(".pdf", "2.pdf")
output_pdf = PdfFileWriter()
py_open_file = open(full_path, "rb") 
with open(full_path, "rb") as f:
    open_pdf = PdfFileReader(f)
    last_page = len(open_pdf.pages)-1
    output_pdf.addPage(open_pdf.getPage(last_page))

outputStream = file(full_path2, "wb")
output_pdf.write(outputStream)
outputStream.close()
```

To resolve the error, I replaced the with/open statement with:

`f = open(full_path, "rb")`

**Comment by mstamy2** [comment]
26e50775ed5fbc36982719b22040454bc1d96cac should allow a graceful exit as in prior to v1.26.0.

I suppose it's a little counterintuitive that input files must remain open during the write process...
