### ISSUE TITLE
PyPDF merge failed with PDF version 1.6 and above

### ISSUE THREAD

**Issue by steltecpy** [mstamy2/PyPDF2#273]
Sometimes and randomly, we fail to generate the new merge PDF document. Most of the time we fail when a PDF version is from 1.6 and above. It appear that PyPDF2 is hardcoded to version 1.3. Our though here is, no matter what it is the file PDF version, as soon we generate the new one, it get generated as 1.3. Sometime, object made in 1.6 can be downgraded to 1.3 version and sometimes not. By opening the PDF document, when we find the offending object, we remove it than PyPDF can generate the PDF. The object removed are very often simple object such as a pen markup. Once in a while, it's a snapshot we paste in the document.

Here our piece of code:

`def merge(first, second, merged):
    """Merge two pdf file into one, first and second argument are path of originals files, and merged argument is the path of the result"""
    output = PyPDF2.PdfFileWriter()
    input1 = PyPDF2.PdfFileReader(file(first, "rb"))
    input2 = PyPDF2.PdfFileReader(file(second, "rb"))
    for page in range(input1.getNumPages()):
        output.addPage(input1.getPage(page))
    for page in range(input2.getNumPages()):
        output.addPage(input2.getPage(page))
    outputStream = file(merged, "wb")
    output.write(outputStream)
    outputStream.close()
`

See PDF in attachement for testing. We also tried the PdfFileMerge and still not able to generate the new PDF.
[SP_COPY_E07-208-AM-U3.5_RevA_$_E07-208-AM-U3.5_RevA.pdf](https://github.com/mstamy2/PyPDF2/files/363692/SP_COPY_E07-208-AM-U3.5_RevA_._E07-208-AM-U3.5_RevA.pdf)
[SP_E07-208-AM-U3.5_RevA_$_E07-208-AM-U3.5_RevA.pdf](https://github.com/mstamy2/PyPDF2/files/363693/SP_E07-208-AM-U3.5_RevA_._E07-208-AM-U3.5_RevA.pdf)

**Comment by mstamy2** [comment]
It appears that the PNG predictor algorithms 3, 4, and 5 (Average, Paeth, and optimum, respectively)  are not yet supported.

They shouldn't be too difficult to implement; we'll work on doing so in the future.

**Comment by steltecpy** [comment]
A question like that.  Is there a manner that we can be notify when a new version of PyPDF2 is released?  So I could follow the notes for bugs and fixes on new release and download the new version if required.

 

 

Patrice Monette

cisc-iccaAIT / Programmer – TI / Programmeur

Steltec_coul_angT:   450-971-5995 x 2221

F:   450-971-1865

**Comment by mstamy2** [comment]
@steltecpy Fixed by #283, will be included in next release.

**Comment by steltecpy** [comment]
Thanks guy!  Can`t wait to see new release J

 

 

Patrice Monette

cisc-iccaAIT / Programmer – TI / Programmeur

Steltec_coul_angT:   450-971-5995 x 2221

F:   450-971-1865
