### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [mstamy2/PyPDF2#313]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [PyPDF2](https://pypi.python.org/pypi/PyPDF2), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install PyPDF2 with just the wheel, without having to do any extra work.

**Comment by ololoe** [comment]
Is it fixed? I installed it with simple pip install.

**Comment by SecT0uch** [comment]
That would be very useful
I'm distributing my software using pynsist.
It allows to import packages on a chosen version only if a .whl is available on pypi.
It would be much more easy to distribute.
Would it be possible to do it and publish future releases with a wheel file ?

**Comment by phaer** [comment]
Wheel support would be free with a one-line-patch to use setuptools, see https://github.com/mstamy2/PyPDF2/issues/465
