### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by einsweniger** [mstamy2/PyPDF2#373]
Hi there!
I wonder if somebody still maintains the project, as Issues and PRs pile up and commits are few and far between.

@mstamy2: if you can't get around to actively maintain the project, would you mind to appoint a volunteer for maintenance?

Just asking, because I'd have some issues to report, but I won't if development was ceased.

best regards,
-1

**Comment by claird** [comment]
No:  in the short term, PyPDF2 is largely unmaintained.

I will happily reboot it, though.  With a little indication--just a few e-mail follow-ups--of how much difference it makes to users to keep it going, I'll resume maintenance from Matthew.  In fact, I have strong ideas about how we can make PyPDF2 better than ever.  My biggest question:  how many users care?

**Comment by moodh** [comment]
We use it daily but due to the state of the project we've decided to change to itext or a more mature library. Personally I like this library and I hope it'll get rebooted. :)

**Comment by einsweniger** [comment]
I played with the thought to rewrite it, or at least create a more pythonic interface.
Initially, i just wanted to access the AcroForm fields, but trying to recurse the tree feels really unwieldy and a little inconsistent.
But if I were to rewrite it, I'd probably drop python2, as I never learned that.
I'd also suggest to integrate at least some of the Isartor or veraPDF files for testing.

**Comment by Rob1080** [comment]
I'm still using it in a few projects.

**Comment by BrianPainter** [comment]
I use it in several projects. Are there other python alternatives? Mostly I need to merge separate PDF's into one, adding newly created PDF's (ReportLab) along the way.

**Comment by oscardssmith** [comment]
I would really like it to be supported as well. I don't know enough about pdfs to be of much help though.

**Comment by sekrause** [comment]
Judging from the number of pull requests there still seems to be a lot of interest in this project.

We're also still using it in a project, but were already starting to think about migrating away simply because this project looks so unmaintained.

**Comment by ganeshtata** [comment]
I have been using this project was several of my projects. It would be awesome if it is continued to be maintained. One of the issues that has been bugging me for a while is  #226.

**Comment by FelixSchwarz** [comment]
I'm also using this and I'd hate to use another C-based library. Also there are some other projects like WeasyPrint which require pypdf2.

**Comment by bdheeman** [comment]
I use it as part of [pdfbooklet](https://github.com/Averell7/PdfBooklet), but also wrote a python script pdfmeta.py for viewing and modifying metadata :-)

Although, the [qpdf](https://github.com/qpdf/qpdf) is required for [cups](https://github.com/apple/cups) now a days, on Linux, but I love using PyPDF2 like anything for merging cover pages and PDF books, sometimes 100 page segments for large books, I create from scanned pages using [jbig2enc](https://github.com/agl/jbig2enc) ;-)

**Comment by soferio** [comment]
We use it for a new webapp (in Python 2.7). Would be great if it were kickstarted again.

**Comment by subCdteOso** [comment]
I'm hoping to use this library for part of an automated manufacturing process. The hope is to use PDFs as a way for customers to upload multi-layered design files. We'd need support for Layers/Optional Content Groups though.

**Comment by snoyes** [comment]
I use it to automatically merge my monthly expense reports with receipts. However, some of those PDFs now produce an error in PyPDF2, even though they are readable with Adobe Acrobat Reader, which has me looking for either a bug fix or a different library.

**Comment by mstamy2** [comment]
I've opened a discussion on #385

**Comment by MartinThoma** [comment]
I've just became the maintainer of this project :-)
