### ISSUE TITLE
Use setuptools?

### ISSUE THREAD

**Issue by phaer** [mstamy2/PyPDF2#465]
Hi,

Maybe I am missing something, but it looks line only a single line needs to be changed
to use `setuptools`:

```diff
-from distutils.core import setup
+from setuptools import setup
```

which would enable users to generate a wheel with

```
python3 setup.py bdist_wheel
```

They issue I've had was that I tried to mirror packages in internal, branch-specific pypi repositories for a CI system and `twine` complained that the `.tar.gz` from pypi.python.org did not include meta data in the package. 

What do you think? Are there any drawbacks or difficulties? I'd be glad to help :)

**Comment by SecT0uch** [comment]
Maybe you should try to make a PR

**Comment by phaer** [comment]
Or maybe you should? Sorry, I mostly opened the issue to help others who depend on PyPDF2 and are trying to build a wheel, but I don't really feel like adding another PR which won't ever be merged to what seems to be a dead project with over 60 open PRs.

**Comment by SecT0uch** [comment]
You seem to know what you're talking about while I don't know setuptools so much.
Anyway it seems indeed to be a dead project
