### ISSUE TITLE
an error in pdf.py

### ISSUE THREAD

**Issue by xupeng1231** [mstamy2/PyPDF2#472]
in pdf.pf file 575 line
`            else:  
                if data.pdf.stream.closed:  
                    raise ValueError("I/O operation on closed file: {}".format(data.pdf.stream.name))
                newobj = externMap.get(data.pdf, {}).get(data.generation, {}).get(data.idnum, None) `
the `data.pdf.stream` stream is undefined

**Comment by 14vv1A0516** [comment]
When trying to encrypt a PDF and write it into a location using PyPDF2 in Python ,I am getting this error . Please help me.

raise utils.PdfReadError("Unable to find 'endstream' marker after stream at byte %s." % utils.hexStr(stream.tell()))
 PdfReadError: Unable to find 'endstream' marker after stream at byte 0xb707.

Please help me.

**Comment by MartinThoma** [comment]
Please check the guide on how to write issues: https://github.com/mstamy2/PyPDF2#issues - if you add the missing information, I'll reopen.
