### ISSUE TITLE
Can PyPDF2 extract images?

### ISSUE THREAD

**Issue by madpiano** [mstamy2/PyPDF2#475]
Sorry if this is a dumb question. I searched "pictures", "JPEG" but got no information. Can anyone tell me if image extraction is possible and maybe point to the module? Thanks in advance!

**Comment by kurtmckee** [comment]
Yes, it's possible. Look in the `Scripts/` directory. There's a file named `pdf-image-extractor.py`. =)

**Comment by kurtmckee** [comment]
@MartinThoma Thanks for closing this ticket.

I see there's a lot of changes landing in the git repo, and that's great! I'll help with bug triage and PR reviews as I have time!
