### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by msb** [mstamy2/PyPDF2#479]
I used following code (copied from an example) to split [this pdf](https://www.doctoruke.com/aintmisbehavinbar.pdf) into pages.

```python3
    inputpdf = PdfFileReader(open("aintmisbehavin.pdf", "rb"))

    for i in range(inputpdf.numPages):
        output = PdfFileWriter()
        output.addPage(inputpdf.getPage(i))
        with open("document-page%s.pdf" % i, "wb") as outputStream:
            output.write(outputStream)
```
I got the following error:
```
Traceback (most recent call last):
  File "./example.py", line 57, in <module>
    inputpdf = PdfFileReader(open("aintmisbehavin.pdf", "rb"), strict=False)
  File "/home/msb/workspaces/home/compile/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/msb/workspaces/home/compile/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1689, in read
    stream.seek(-1, 2)
OSError: [Errno 22] Invalid argument
```

**Comment by msb** [comment]
my apologies - raised in error

**Comment by MRigal** [comment]
@msb I have the same issue and I don't understandd where it comes from...

**Comment by MRigal** [comment]
OK it had to do with the fact I was using an outdated version of wkhtml2pdf, had to download the github binaries for this

**Comment by ezhilan03** [comment]
> my apologies - raised in error



> I used following code (copied from an example) to split [this pdf](https://www.doctoruke.com/aintmisbehavinbar.pdf) into pages.
> 
> ```python
>     inputpdf = PdfFileReader(open("aintmisbehavin.pdf", "rb"))
> 
>     for i in range(inputpdf.numPages):
>         output = PdfFileWriter()
>         output.addPage(inputpdf.getPage(i))
>         with open("document-page%s.pdf" % i, "wb") as outputStream:
>             output.write(outputStream)
> ```
> 
> I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "./example.py", line 57, in <module>
>     inputpdf = PdfFileReader(open("aintmisbehavin.pdf", "rb"), strict=False)
>   File "/home/msb/workspaces/home/compile/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1084, in __init__
>     self.read(stream)
>   File "/home/msb/workspaces/home/compile/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1689, in read
>     stream.seek(-1, 2)
> OSError: [Errno 22] Invalid argument
> ```

what is the solution for this

**Comment by ezhilan03** [comment]
what is the solution for this error?
