### ISSUE TITLE
HTML links not clickable after merge

### ISSUE THREAD

**Issue by hsrky** [mstamy2/PyPDF2#54]
I have two PDFs to merge, once with HTML links, and another just plain watermarks.

After merging, the links are not working, and if I reverse the merge sequence, the watermarks will hide the links.

Here is my codes:

        bg = PdfFileReader(file("/tmp/bg.pdf", "rb")) #plain watermarks
        fg = PdfFileReader(file("/tmp/fg.pdf", "rb"))   #text with links
        
        page = bg.getPage(0)
        page.mergePage(fg.getPage(0))
        
        output = PdfFileWriter()
        output.addPage(page)
        
        ostream = file('/tmp/out.pdf', 'wb')
        output.write(ostream)
        ostream.close()

**Comment by aryanmediratta** [comment]
I'm facing the same issue.. I looked at the commit and I think it should've handled it automatically. Any ideas what could have went wrong? Code Snippet: 
`packet = BytesIO()
can = canvas.Canvas(packet, pagesize=letter)
can.drawString(70, 40, 'Watermark')
 can.save()

 packet.seek(0)
 new_pdf = PdfFileReader(packet)
 input_buffer = BytesIO(pdf_file)
 existing_pdf = PdfFileReader(input_buffer)
 output = PdfFileWriter()

 i = 0
 for i in range(existing_pdf.getNumPages()):
 page = existing_pdf.getPage(i)
 page.mergePage(new_pdf.getPage(0))
 output.addPage(page)
 out = BytesIO()`
