### ISSUE TITLE
assert len(data) % rowlength == 0 fails for the PNG in this PDF

### ISSUE THREAD

**Issue by Biganon** [mstamy2/PyPDF2#542]
Hi, I'm using [this PDF file](https://idrh.ku.edu/sites/idrh.ku.edu/files/files/tutorials/pdf/Non-text-searchable.pdf) with the script **pdf-image-extractor.py** that's provided in Scripts (a modified version, that uses page 0 instead of page 30; the code works for my other PDF files).

When calling `getData()` on the only image in the PDF, whose parameters are:

`{'/Subtype': '/Image', '/ColorSpace': '/DeviceRGB', '/Width': 2550, '/Height': 3300, '/BitsPerComponent': 8, '/Filter': '/FlateDecode', '/DecodeParms': {'/Predictor': 15, '/Columns': 2550, '/Colors': 3}}`

, the decompression seems to work, but immediately after, PyPDF2 fails to apply the filters as needed. The assert, at line 129 of **filters.py**, fails. I tried deactivating it (using `python -O`), but sure enough, it doesn't work (random bytes are wrongly used as the filter identifier, bytes such as 255, 154, 144...).

You might answer "this PDF is broken", but what I don't understand is every PDF viewer is able to display it just fine. I even used an online PDF validity checking tool, which reported no issues whatsoever.

The length of the data is 25248300, the number of columns is 2550, so the assertion would work if 25248300 was divisible by 2551, which it isn't.

Might be useful: when using Image.frombytes and passing the data directly, [an image is produced, which _kinda_ resembles the correct one, but its colors are inverted, and it's slanted towards the right](https://i.imgur.com/EiOk7aB.png). I'm almost certain that there's an offset, that the reported length of the scanlines is incorrect or something like that... but how do PDF viewers manage to show the PDF perfectly? Are they using some kind of heuristic approach to "fix" the offset in the data?

Thanks in advance!

**Comment by Biganon** [comment]
OK, thanks to a friend I found out that filters.py never uses /Colors, which in this case equals 3. The `row_length` should be equal to `columns * colors + 1`. But even then, decode() return a string instead of a bytes object, so it cannot be used directly.

I tried with PyPDF4, which returns bytes, and now it's slightly better: the image that's produced has the correct colors (white background, black text), but it's still slightly slanted.

**Comment by Biganon** [comment]
Solved. It implied a few changes to filters.py, I'll try and write a PR tomorrow.

**Comment by aleonnet** [comment]
Hi @Biganon,
I'm having the same issue using PyPDF4. How did you solved the issue? What were the changes to filters.py?
Thank you
Alessandro

data = xObject[obj].getData()
  File "/usr/local/lib/python3.8/site-packages/PyPDF4/generic.py", line 843, in getData
    decoded._data = filters.decodeStreamData(self)
  File "/usr/local/lib/python3.8/site-packages/PyPDF4/filters.py", line 401, in decodeStreamData
    data = FlateDecode.decode(data, stream.get("/DecodeParms"))
  File "/usr/local/lib/python3.8/site-packages/PyPDF4/filters.py", line 156, in decode
    raise PdfReadError("Unsupported PNG filter %r" % filterByte)
PyPDF4.utils.PdfReadError: Unsupported PNG filter 255
