### ISSUE TITLE
NotImplementedError: unsupported filter /JBIG2Decode

### ISSUE THREAD

**Issue by zoj613** [mstamy2/PyPDF2#549]
Getting this error for an image: `NotImplementedError: unsupported filter /JBIG2Decode` when calling the `.getData()` method on an image inside a pdf. Any way to get around this?

**Comment by infelane** [comment]
Same problem.
From what I found on the net, there is no real way around it atm.
My current workaround will be to just export the whole page as an image with pdf2image.
