### ISSUE TITLE
'charmap' codec can't encode character '\u02d8'

### ISSUE THREAD

**Issue by kartikeyangupta** [mstamy2/PyPDF2#560]
Getting the error while extracting text of a PDF
I am extracting the PDF file from a zipfile using zipfile library and reading the file, throws me this error.
```
Traceback (most recent call last):
  File "code.py", line 23, in <module>
    print(pageObj.extractText())
  File "C:\Users\user\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u02d8' in position 8: character maps to <undefined>
```

**Comment by tripleee** [comment]
The problem is not in PyPDF2; the problem is that your output device is configured to use a Windows code page which cannot display the text you extracted.
