### ISSUE TITLE
 python3 -m unittest Tests.testscd fails

### ISSUE THREAD

**Issue by debragail** [mstamy2/PyPDF2#564]
python3 -m unittest Tests.testscd
E
======================================================================
ERROR: Tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: Tests
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'Tests'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
os-MacBook-Air:Resources op$ cd ..
os-MacBook-Air:PyPDF2-1.26.0 op$ cd ..
os-MacBook-Air:code op$ git clone git@github.com:mstamy2/PyPDF2.git
Cloning into 'PyPDF2'...
remote: Enumerating objects: 1827, done.
remote: Total 1827 (delta 0), reused 0 (delta 0), pack-reused 1827
Receiving objects: 100% (1827/1827), 1.95 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (1097/1097), done.
os-MacBook-Air:code op$ cd PyPDF2
os-MacBook-Air:PyPDF2 op$ ls
CHANGELOG	MANIFEST.in	PyPDF2		Resources	Scripts		setup.py
LICENSE		PDF_Samples	README.md	Sample_Code	Tests		tox.ini
os-MacBook-Air:PyPDF2 op$ cd Tests
os-MacBook-Air:Tests op$ python -m unittest Tests.tests
E
======================================================================
ERROR: Tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: Tests
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'Tests'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)`

**Comment by MartinThoma** [comment]
I recommend to use `pytest` just as we now do in CI : https://github.com/mstamy2/PyPDF2/blob/master/.github/workflows/unit-tests.yaml#L36
