### ISSUE TITLE
Expected object ID (29 0) does not match actual (28 0); xref table not zero-indexed

### ISSUE THREAD

**Issue by artikhot97** [mstamy2/PyPDF2#566]
In that given error while merging with PdfFileMerger
Its thought **PdfReadError: file has not been decrypted.** 
```
 merger = PdfFileMerger()
 if result != 0:
    merger.append(result)
 for fileobj in fileobjList:
       merger.append(fileobj)
```

Python 2.7 

Can someone help me with that error 

Even I tried with the **strict=False**  in PdfFileMerger it works but it just suppress the error and warning not fix the issue.

Thanks in Advance

**Comment by MartinThoma** [comment]
Please check the guide on how to write issues: https://github.com/mstamy2/PyPDF2#issues - if you add the missing information, I'll reopen.
