### ISSUE TITLE
Is PyPDF2 dead? Is there an alive fork?

### ISSUE THREAD

**Issue by MartinThoma** [mstamy2/PyPDF2#571]
The last commit was from 2018, there are 87 open PRs and 263 open issues. It seems as if the project is dead. Is there an alive fork?

**Comment by franp9am** [comment]
May be related... https://stackoverflow.com/questions/63199763/maintained-alternatives-to-pypdf2

**Comment by shun-lin** [comment]
> May be related... https://stackoverflow.com/questions/63199763/maintained-alternatives-to-pypdf2

Thanks!

**Comment by balupton** [comment]
The author's last activity on github was actually this issue:
https://github.com/mstamy2/PyPDF2/issues/477

Which links here:
https://github.com/mstamy2/PyPDF2/wiki/State-of-PyPDF2-and-Future-Plans

**Comment by MartinThoma** [comment]
I'm now the maintainer is PyPDF2 😁
