### ISSUE TITLE
MergePage rotates 1 page relative to the other, in certain pdfs

### ISSUE THREAD

**Issue by Rob1080** [mstamy2/PyPDF2#58]
I'm merging 2 pdfs using code that works correctly for other pdfs. I'm using the mergePage method to overlay the content from one pdf on the other pdf (merge page by page).
In the image below, the numbers (highlighted by red box) should be positioned vertically. 

![capture](https://f.cloud.github.com/assets/2420259/1953015/499d51ca-81b4-11e3-8c43-fb8b4bb0f0f2.PNG)

The "base pdf" is a scan from a Xerox WorkCentre 7435. The "secondary pdf" (containing the highlighted numbers) is generated using reportlab. The "base pdf" and "secondary pdf" have portrait orientation when viewing in a pdf viewer. 
Other scans (from other scanners) merge correctly.

I don't know much about how pdf structure works, but is it possible the scan isn't including some data (orientation)?

I will try include a problem pdf when I obtain one that doesn't contain sensitive information.
Thanks
Rob

**Comment by Rob1080** [comment]
Ended up using mergeRotatedTranslatedPage to resolve the issue.

```python
page_x.mergeRotatedTranslatedPage(page_y, rotation, page_y.mediaBox.getWidth()/2, page_y.mediaBox.getWidth()/2)
```

**Comment by eamanu** [comment]
Hi  @Rob1080..

I know this is a very old issue and I have the same issue. I don't know if

```page_x.mergeRotatedTranslatedPage(page_y, rotation, page_y.mediaBox.getWidth()/2, page_y.mediaBox.getWidth()/2)}```

is a good solution for this issue, because, ok I can rotate and merge the page with "/Rotate" attribute but I have to "guess" the value of x and y to rotate.
