### ISSUE TITLE
Neither PIP or easy_install will install pyPDF2 ???

### ISSUE THREAD

**Issue by BobTuit** [mstamy2/PyPDF2#581]
C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin>python -m pip install pdfreader
Collecting pdfreader
  Using cached https://files.pythonhosted.org/packages/e6/1b/9f6a43eb1e685ae7c2283e30bd7e35a8c0e42becb7a6098866dae9fe8cd5/pdfreader-0.1.5.tar.gz
Collecting bitarray>=1.1.0 (from pdfreader)
  Using cached https://files.pythonhosted.org/packages/79/e8/7c8fafd17338bd2efdde30376903d13859bfecc24d564a5c1538b3a09338/bitarray-1.6.1.tar.gz
Collecting pillow>6.2.0 (from pdfreader)
  Downloading https://files.pythonhosted.org/packages/2b/65/e4a5130b4162d20ed99ff096549a04d18f050cfcdb16fe1643ac751c0181/Pillow-8.0.1-cp37-cp37m-win_amd64.whl (2.1MB)

C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin>python -m pip install pdfreader
Collecting pdfreader
  Using cached pdfreader-0.1.5.tar.gz (2.8 MB)
Collecting bitarray>=1.1.0
  Using cached bitarray-1.6.1.tar.gz (55 kB)
Collecting pillow>6.2.0
  Using cached Pillow-8.0.1-cp37-cp37m-win_amd64.whl (2.1 MB)
Using legacy 'setup.py install' for pdfreader, since package 'wheel' is not installed.
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Installing collected packages: bitarray, pillow, pdfreader
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bob.I7SMALL\\AppData\\Local\\Temp\\pip-install-z04a5c32\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\bob.I7SMALL\\AppData\\Local\\Temp\\pip-install-z04a5c32\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bob.I7SMALL\AppData\Local\Temp\pip-record-oedxdu27\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\Include\bitarray'
         cwd: C:\Users\bob.I7SMALL\AppData\Local\Temp\pip-install-z04a5c32\bitarray\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\bitarray
    copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.7\bitarray
    copying bitarray\test_util.py -> build\lib.win-amd64-3.7\bitarray
    copying bitarray\util.py -> build\lib.win-amd64-3.7\bitarray
    copying bitarray\__init__.py -> build\lib.win-amd64-3.7\bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\bitarray
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files\Blender Foundation\Blender 2.82\2.82\python\include" "-IC:\Program Files\Blender Foundation\Blender 2.82\2.82\python\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcbitarray/_bitarray.c /Fobuild\temp.win-amd64-3.7\Release\bitarray/_bitarray.obj
    _bitarray.c
    bitarray/_bitarray.c(13): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bob.I7SMALL\\AppData\\Local\\Temp\\pip-install-z04a5c32\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\bob.I7SMALL\\AppData\\Local\\Temp\\pip-install-z04a5c32\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bob.I7SMALL\AppData\Local\Temp\pip-record-oedxdu27\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\Include\bitarray' Check the logs for full command output.
**********************************************************************************************************
C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin>python -m easy_install pdfreader
Searching for pdfreader
Reading https://pypi.org/simple/pdfreader/
Downloading https://files.pythonhosted.org/packages/e6/1b/9f6a43eb1e685ae7c2283e30bd7e35a8c0e42becb7a6098866dae9fe8cd5/pdfreader-0.1.5.tar.gz#sha256=4f1b88577a14d39a3951893990bf3316231fe78e690a7e83bfb6916ab083f28a
Best match: pdfreader 0.1.5
Processing pdfreader-0.1.5.tar.gz
Writing C:\Users\bob.I7SMALL\AppData\Local\Temp\easy_install-1feep551\pdfreader-0.1.5\setup.cfg
Running pdfreader-0.1.5\setup.py -q bdist_egg --dist-dir C:\Users\bob.I7SMALL\AppData\Local\Temp\easy_install-1feep551\pdfreader-0.1.5\egg-dist-tmp-0d18dk8o
warning: no files found matching 'LICENSE'
warning: no files found matching '*.conf' under directory 'doc'
no previously-included directories found matching 'venv'
no previously-included directories found matching '.venv'
no previously-included directories found matching 'doc\_build'
no previously-included directories found matching 'dist'
warning: no previously-included files found matching 'example-crash-markdown.txt'
warning: no previously-included files found matching 'extract-logo.png'
warning: no previously-included files found matching 'fax-from-p8.png'
warning: no previously-included files found matching 'mask.png'
warning: no previously-included files found matching 'sample-cmap.txt'
warning: no previously-included files found matching 'sample-font.type1'
creating c:\program files\blender foundation\blender 2.82\2.82\python\lib\site-packages\pdfreader-0.1.5-py3.7.egg
Extracting pdfreader-0.1.5-py3.7.egg to c:\program files\blender foundation\blender 2.82\2.82\python\lib\site-packages
Adding pdfreader 0.1.5 to easy-install.pth file

Installed c:\program files\blender foundation\blender 2.82\2.82\python\lib\site-packages\pdfreader-0.1.5-py3.7.egg
Processing dependencies for pdfreader
Searching for pillow>6.2.0
Reading https://pypi.org/simple/pillow/
Downloading https://files.pythonhosted.org/packages/2b/65/e4a5130b4162d20ed99ff096549a04d18f050cfcdb16fe1643ac751c0181/Pillow-8.0.1-cp37-cp37m-win_amd64.whl#sha256=e38d58d9138ef972fceb7aeec4be02e3f01d383723965bfcef14d174c8ccd039
Best match: Pillow 8.0.1
Processing Pillow-8.0.1-cp37-cp37m-win_amd64.whl
Installing Pillow-8.0.1-cp37-cp37m-win_amd64.whl to c:\program files\blender foundation\blender 2.82\2.82\python\lib\site-packages
Adding Pillow 8.0.1 to easy-install.pth file

Installed c:\program files\blender foundation\blender 2.82\2.82\python\lib\site-packages\pillow-8.0.1-py3.7-win-amd64.egg
Searching for bitarray>=1.1.0
Reading https://pypi.org/simple/bitarray/
Downloading https://files.pythonhosted.org/packages/79/e8/7c8fafd17338bd2efdde30376903d13859bfecc24d564a5c1538b3a09338/bitarray-1.6.1.tar.gz#sha256=ab85b38365dd9956264226b30dababa02161ed49bb36c7ee82cc6545e07b1599
Best match: bitarray 1.6.1
Processing bitarray-1.6.1.tar.gz
Writing C:\Users\bob.I7SMALL\AppData\Local\Temp\easy_install-o16ll536\bitarray-1.6.1\setup.cfg
Running bitarray-1.6.1\setup.py -q bdist_egg --dist-dir C:\Users\bob.I7SMALL\AppData\Local\Temp\easy_install-o16ll536\bitarray-1.6.1\egg-dist-tmp-f6xb2kcv
_bitarray.c
bitarray/_bitarray.c(13): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by MartinThoma** [comment]
Can any Windows user confirm this issue?
