### ISSUE TITLE
EOF marker not found error in python

### ISSUE THREAD

**Issue by shubham-kamlaskar** [mstamy2/PyPDF2#616]
How to Fix PyPDF Error: EOF Marker Not Found”

Im getting above error at the time of PDF file opening 

PyPDF2.utils.PdfReadError: EOF marker not found

**Comment by deepaksen1996** [comment]
Try strict=False in pdf reader. It may solve the problem.

**Comment by MartinThoma** [comment]
It's a duplicate of https://github.com/py-pdf/PyPDF2/issues/442 - let's keep track of it there
