### ISSUE TITLE
DeprecationWarning: invalid escape sequence \c

### ISSUE THREAD

**Issue by maradragan** [mstamy2/PyPDF2#638]
I am using PyPDF2 1.26.0 with python 3.7 and I get the following warning:

/usr/local/lib/python3.7/site-packages/PyPDF2/generic.py:353: DeprecationWarning: invalid escape sequence \c
  tok = b_("\c")

**Comment by MartinThoma** [comment]
This was fixed with https://github.com/mstamy2/PyPDF2/commit/dacc6b75eb02b2eb2eea7b54e45ca23f5d08b378

I'd be happy about a recession test, though
