### ISSUE TITLE
PyPDF2 is dead, use pikepdf instead

### ISSUE THREAD

**Issue by sekrause** [mstamy2/PyPDF2#647]
Since PyPDF2 is completely unmaintained and the developer doesn't react to anything anymore, let me "abuse" this issue to tell everyone that you shouldn't really use PyPDF2 anymore and that there is now a much better replacement: [pikepdf](https://github.com/pikepdf/pikepdf), which is actively maintained, much faster and much more reliable. So stop wasting your time writing issues or pull-requests here and port your applications to pikepdf.

I'm not involved in the pikepdf project, but have been a happy user of this library for at least a year after being a former PyPDF2 user.

**Comment by rassie** [comment]
`pikepdf` is great, except when it isn't, e.g. https://github.com/pikepdf/pikepdf/issues/227 has bitten me hard. Always evaluate first before jumping the ship.

**Comment by vasmedvedev** [comment]
Did you have do a lot of refactoring moving to `pikepdf`?

**Comment by johns1c** [comment]
There are several pyPDF2 clones 
     PyPDF3 and PyPDF4 
they are python only and have a few improvements.

I created a clone of my own at a time when PyPDF2 did not work with  Python3.   Over time have added support for a number of things such as PNG images but the main improvement is that it can parse  to_unicode tables and this significantly  improves text extraction.  It has no installer - I just download and overwrite the PIP install PyPDF2 code.

**Comment by MartinThoma** [comment]
I just became the maintainer of PyPDF2 :-)

Yesterday+today I've merged roughly 20 PRs, tomorrow I hope I can go through 5-10 more. The key point for the moment is to increase test coverage.

As this is not one specific issue about PyPDF2, I'm now closing it. Feel free to open new ones about PyPDF2
